/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as dankFairLaunchSol from "./DANKFairLaunch.sol";
export type { dankFairLaunchSol };
export type { BaseToken } from "./BaseToken";
export type { DankToken } from "./DankToken";
export type { Lock } from "./Lock";
