/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DANKFairLaunch } from "./DANKFairLaunch";
export type { IDANKFairLaunch } from "./IDANKFairLaunch";
